#!/bin/bash

# MiniMax Studio - Deploy to Vercel
# ONE COMMAND DEPLOYMENT! 🚀

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║           🚀 VERCEL DEPLOYMENT - READY TO GO! 🚀               ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Vercel CLI: INSTALLED (v48.10.11)"
echo "✅ Project: CONFIGURED"
echo "✅ Next.js: READY"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1. Vercel will open browser for login (if first time)"
echo "2. Authorize with GitHub/GitLab/Bitbucket/Email"
echo "3. Vercel auto-detects Next.js settings ✅"
echo "4. Deploys to production"
echo "5. Gives you LIVE URL!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 STARTING DEPLOYMENT..."
echo ""

# Run vercel deploy
vercel --prod

if [ $? -eq 0 ]; then
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║                                                                ║"
    echo "║                  ✅ DEPLOYMENT COMPLETE! ✅                    ║"
    echo "║                                                                ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "🎉 YOUR SITE IS LIVE!"
    echo ""
    echo "Check the URL above ☝️"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "✨ NEXT STEPS:"
    echo ""
    echo "1. Open your Vercel URL"
    echo "2. Click 'No API Key' button"
    echo "3. Add MiniMax API key from: https://platform.minimax.io"
    echo "4. Start creating AI content! 🎨🎬🎵💻"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "💡 TIPS:"
    echo ""
    echo "• Custom domain: vercel.com → Project → Domains"
    echo "• Analytics: vercel.com → Project → Analytics"
    echo "• Auto-deploy: Push to GitHub = Auto deploy!"
    echo ""
    echo "🚀 ENJOY YOUR AI STUDIO ON VERCEL! 🚀"
    echo ""
else
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "❌ DEPLOYMENT FAILED"
    echo ""
    echo "Common fixes:"
    echo ""
    echo "1. Authentication issue?"
    echo "   → Run: vercel login"
    echo "   → Try again: ./deploy-vercel.sh"
    echo ""
    echo "2. Want to try again?"
    echo "   → ./deploy-vercel.sh"
    echo ""
fi
