#!/bin/bash

# MiniMax Studio - Deployment Commands
# Copy and run these commands one by one

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║           🚀 MiniMax Studio - Ready to Deploy! 🚀              ║"
echo "║                                                                ║"
echo "╔════════════════════════════════════════════════════════════════╗"
echo ""
echo "📍 Current location: $(pwd)"
echo "✅ Git status:"
git log --oneline -3
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 STEP 1: Create GitHub Repository"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Go to: https://github.com/new"
echo ""
echo "Fill in:"
echo "  • Repository name: minimax-studio"
echo "  • Description: AI Content Generation Platform with MiniMax API"
echo "  • Public or Private: Your choice"
echo "  • ❌ DON'T check 'Initialize with README'"
echo "  • Click 'Create repository'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
read -p "✋ Press Enter after creating the repository on GitHub..."
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 STEP 2: What's your GitHub username?"
echo "════════════════════════════════════════════════════════════════"
echo ""
read -p "GitHub username: " USERNAME
echo ""

if [ -z "$USERNAME" ]; then
    echo "❌ Username required! Run the script again."
    exit 1
fi

REPO_URL="https://github.com/$USERNAME/minimax-studio.git"

echo "Your repository URL: $REPO_URL"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 STEP 3: Connecting to GitHub..."
echo "════════════════════════════════════════════════════════════════"
echo ""

# Check if remote exists
if git remote get-url origin &> /dev/null; then
    echo "🔄 Updating existing remote..."
    git remote set-url origin "$REPO_URL"
else
    echo "➕ Adding remote..."
    git remote add origin "$REPO_URL"
fi

echo "✅ Remote configured!"
echo ""
git remote -v
echo ""

echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 STEP 4: Pushing to GitHub..."
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "You may be asked for credentials..."
echo ""

git branch -M main
git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║                                                                ║"
    echo "║                   ✅ SUCCESS! CODE PUSHED! ✅                  ║"
    echo "║                                                                ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "🔗 Your repo: https://github.com/$USERNAME/minimax-studio"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "📝 FINAL STEP: Deploy to Netlify"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "1. Open: https://app.netlify.com (sign up if needed - FREE!)"
    echo ""
    echo "2. Click: 'Add new site' → 'Import an existing project'"
    echo ""
    echo "3. Choose: 'GitHub'"
    echo "   (Authorize Netlify if first time)"
    echo ""
    echo "4. Select repository: 'minimax-studio'"
    echo ""
    echo "5. Build settings (should be auto-detected):"
    echo "   ✓ Build command: npm run build"
    echo "   ✓ Publish directory: .next"
    echo "   ✓ Already configured in netlify.toml!"
    echo ""
    echo "6. Click: 'Deploy site'"
    echo ""
    echo "⏱️  Wait 2-3 minutes for build to complete..."
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "🎉 YOUR SITE WILL BE LIVE!"
    echo ""
    echo "Default URL: https://random-name-123.netlify.app"
    echo ""
    echo "Customize it:"
    echo "  • Site settings → Domain management"
    echo "  • Options → Edit site name"
    echo "  • Change to: minimax-studio-yadu"
    echo "  • New URL: https://minimax-studio-yadu.netlify.app"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "✨ AFTER DEPLOYMENT:"
    echo ""
    echo "1. Open your Netlify URL"
    echo "2. Click 'No API Key' button in header"
    echo "3. Add MiniMax API key from: https://platform.minimax.io"
    echo "4. Start creating! 🎨🎬🎵💻"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "🚀 DEPLOYMENT COMPLETE! 🚀"
    echo ""
    echo "Questions? Check:"
    echo "  • NETLIFY.md - Complete guide"
    echo "  • README.md - Full documentation"
    echo "  • COMMANDS.txt - Quick reference"
    echo ""
else
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "❌ PUSH FAILED"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "Common fixes:"
    echo ""
    echo "1️⃣  Authentication Issue?"
    echo "   Generate GitHub Personal Access Token:"
    echo "   • Go to: https://github.com/settings/tokens"
    echo "   • Click: Generate new token (classic)"
    echo "   • Select: repo (full control)"
    echo "   • Copy the token"
    echo "   • Use as PASSWORD when git asks"
    echo ""
    echo "2️⃣  Repository doesn't exist?"
    echo "   • Make sure you created it on GitHub"
    echo "   • Check name: minimax-studio"
    echo "   • Verify URL: $REPO_URL"
    echo ""
    echo "3️⃣  Try again:"
    echo "   ./DEPLOY_STEPS.sh"
    echo ""
fi
